kind: pipeline
type: docker
name: default

steps:
- name: docker_build
  image: plugins/docker
  pull: never
  settings:
    repo: 0xb1b1/android-21
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

